version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  manager:
    build: ./manager
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - redis

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - manager